#!/usr/bin/env bash
set -e
set -x

# parameter $1 is the project list file generated by the baseline_history.sh script
export project_revisions=`cat ${1}`
export repo_name=${2}
export repo_init_tag=${3}
export repo_submodules=${4}
export gitignore_file=${5}

export gitrepo_project_original="scars"
export gitrepo_project_submodule="scars"

#initialize repo
if [ ! -e ${repo_name} ] ; then
    git clone --recursive ssh://git@dtdkcphlx0231.md-man.biz:7998/${gitrepo_project_submodule}/${repo_name}.git
    cd ${repo_name}
    git reset --hard ${repo_init_tag}

    export GIT_AUTHOR_DATE="11/11/70 11:11 AM"
    export GIT_COMMITTER_DATE="11/11/70 11:11 AM"

    test "${gitignore_file}x" != "x" && test -e ${gitignore_file} && cp ${gitignore_file} ./.gitignore

    git add -A .
    git status

    git commit -m "$repo_init_tag" --allow-empty --amend --reset-author
    git tag -a -m $(git tag -l --format '%(contents)' ${repo_init_tag}) ${repo_name}/${repo_init_tag}/${repo_init_tag}

    unset GIT_AUTHOR_DATE
    unset GIT_COMMITTER_DATE

    git reset --hard ${repo_name}/${repo_init_tag}/${repo_init_tag}
    git clean -xffd
    pwd
    # we are still in the root repo
else
    echo "Already cloned and initialized - skip "
    git fetch -ap
    pwd
    cd ${repo_name}
fi


for project_revision in ${project_revisions}; do
    ccm_project_name=`echo ${project_revision} | awk -F"@@@" '{print $1}' | awk -F"~" '{print $1}'`

    repo_convert_rev_tag=`echo ${project_revision} | awk -F"@@@" '{print $1}' | awk -F"~" '{print $2}'`
    ccm_baseline_obj_this=$(ccm query "has_project_in_baseline('${ccm_project_name}~$(echo ${repo_convert_rev_tag} | sed -e 's/xxx/ /g'):project:1') and release='$(ccm query "name='${ccm_project_name}' and version='$(echo ${repo_convert_rev_tag} | sed -e 's/xxx/ /g')' and type='project'" -u -f "%release")'" -u -f "%objectname" | head -1 )
    ccm_component_release=`ccm attr -show release "${ccm_project_name}~$(echo ${repo_convert_rev_tag} | sed -e 's/xxx/ /g'):project:1" | sed -e 's/ //g'`

    if [ "${ccm_baseline_obj_this}X" != "X" ]; then
        ccm_baseline_status_this=`ccm attr -show status "${ccm_baseline_obj_this}" |  cut -c1-3 `
    else
        ccm_baseline_status_this=`ccm attr -show status "${ccm_project_name}~$(echo ${repo_convert_rev_tag} | sed -e 's/xxx/ /g'):project:1" |  sed -e 's/ //g' |  cut -c1-3`
    fi

    repo_convert_rev_tag_wcomponent_wstatus="${ccm_project_name}/${repo_convert_rev_tag}_${ccm_baseline_status_this}"

    if [ `git describe ${repo_convert_rev_tag_wcomponent_wstatus}` ] ; then
      continue
    fi

    git fetch --tags

    # Get the right content
    if [ `git describe ${repo_convert_rev_tag}`  ] ; then
        # we do have the correct 'content' tag checkout it out
        repo_submodule_rev_wcomponent_wstatus=$(git tag | grep .*/.*/${repo_convert_rev_tag}_[dprtis][eueenq][lblsta]$ || echo )
        git reasdfset --hard ${repo_convert_rev_tag}  || git reset --hard ${repo_submodule_rev_wcomponent_wstatus}
    else
        # we do not have the 'content' tag available - investigate its history if it exists ( e.g. missing in repo )
        ccm-baseline-history-get-root.sh "${ccm_project_name}~$(echo ${repo_convert_rev_tag} | sed -e 's/xxx/ /g')"
        exit 1
    fi

    git clean -xffd

    repo_baseline_rev_tag=`echo ${project_revision} | awk -F"@@@" '{print $2}' | awk -F"~" '{print $2}'`
    ccm_baseline_obj_baselineproj=$(ccm query "has_project_in_baseline('${ccm_project_name}~$(echo ${repo_baseline_rev_tag} | sed -e 's/xxx/ /g'):project:1') and release='$(ccm query "name='${ccm_project_name}' and version='$(echo ${repo_baseline_rev_tag} | sed -e 's/xxx/ /g')' and type='project'" -u -f "%release")'" -u -f "%objectname" | head -1 )
    if [ "${repo_baseline_rev_tag}" == "init" ]; then
        repo_baseline_rev_tag_wcomponent_wstatus="${repo_name}/${repo_init_tag}/${repo_init_tag}"
    else
        #ccm_baseline_component_release=`ccm attr -show release "${ccm_project_name}~$(echo ${repo_baseline_rev_tag} | sed -e 's/xxx/ /g'):project:1" |  sed -e 's/ //g'`
        if [ "${ccm_baseline_obj_baselineproj}X" != "X" ]; then
            ccm_baseline_status_baseline=`ccm attr -show status "${ccm_baseline_obj_baselineproj}" |  cut -c1-3 `
        else
            ccm_baseline_status_baseline=`ccm attr -show status "${ccm_project_name}~$(echo ${repo_baseline_rev_tag} | sed -e 's/xxx/ /g'):project:1" |  sed -e 's/ //g' |  cut -c1-3`
        fi
        repo_baseline_rev_tag_wcomponent_wstatus="${ccm_project_name}/${repo_baseline_rev_tag}_${ccm_baseline_status_baseline}"
    fi

    # Move the workarea pointer to the 'baseline' tag
    git reset --mixed ${repo_baseline_rev_tag_wcomponent_wstatus}
    git checkout HEAD .gitignore
    git status

    for repo_submodule in ${repo_submodules}; do
        repo_submodule_rev=`ccm query "hierarchy_project_members('${ccm_project_name}~$(echo ${repo_convert_rev_tag} | sed -e 's/xxx/ /g'):project:1',none) and name ='${repo_submodule}'" -u -f "%version" | sed -e 's/ /xxx/g'`
        if [ "${repo_submodule_rev}X" == "X" ] ; then
            echo "The submodule does not exit as a project - skip"
            continue
        fi
        git checkout HEAD .gitmodules || echo ".gitmodules does not exist in current revision"
        if [ ! `git checkout HEAD ${repo_submodule}` ] ; then
                git rm -rf ${repo_submodule} || rm -rf ${repo_submodule}
                git submodule add --force afds/${gitrepo_project_submodule}/${repo_submodule}.git
        fi
        git submodule update --init --recursive

        cd ${repo_submodule}

        git fetch --tags

        if [ `git describe ${repo_convert_rev_tag_wcomponent_wstatus}` ] ; then
            # we already have the correct tag, so just set it and move on..
            git checkout ${repo_submodule_rev}
            git clean -xffd
            repo_submodule_rev=""
            cd -
            continue
        fi

        repo_submodule_rev_wcomponent_wstatus=$(git tag | grep .*/.*/${repo_submodule_rev}_[dprtis][eueenq][lblsta]$ || echo )

        if [ `git describe ${repo_submodule_rev_wcomponent_wstatus}`  ] ; then
            # we do have the correct 'content' tag checkout it out
            git checkout ${repo_submodule_rev_wcomponent_wstatus}
            git clean -xffd
        else
            # we do not have the 'content' tag available - investgate its root
            cd $(dirname $0)
            ccm-baseline-history-get-root.sh "${repo_submodule}~$(echo ${repo_submodule_rev} | sed -e 's/xxx/ /g')"
            exit 1
        fi

        git tag -f -a -m "Please see tag in master repo for info: ${repo_convert_rev_tag_wcomponent_wstatus}" ${repo_convert_rev_tag_wcomponent_wstatus}

        git push origin -f --tag ${repo_convert_rev_tag_wcomponent_wstatus}

        repo_submodule_rev=""
        cd -

    done
    git status
    git add -A .
    #git status

    export GIT_AUTHOR_DATE=$(git tag -l --format="%(taggerdate:iso8601)" ${repo_convert_rev_tag} | awk -F" " '{print $1 " " $2}')
    export GIT_COMMITTER_DATE=${GIT_AUTHOR_DATE}

    git commit -C ${repo_convert_rev_tag} --reset-author || ( echo "Empty commit.." )

    git tag -a -F ./tag_meta_data.txt ${repo_convert_rev_tag_wcomponent_wstatus}

    rm -f ./tag_meta_data.txt

    unset GIT_AUTHOR_DATE
    unset GIT_COMMITTER_DATE
    unset repo_convert_rev_tag_wcomponent_wstatus


#    git push origin -f --tag ${repo_convert_rev_tag_wcomponent_wstatus}

    echo "============================================================================"
    echo " NEXT "
    echo "============================================================================"

done

